import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vuorivillen Kennel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <header>
      <div className="text-4xl font-semibold text-slate-500 text-center">
        <h1>Vuorivillen Kennel</h1>
        <p className="text-2xl text-slate-200">Coming Soon!</p>
      </div>
    </header>
  );
  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-6 py-6 text-center mb-1">
        <h3>Antti Koponen TMI</h3>
      </div>
    </footer>
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
